### ISSUE TITLE
'undefined: "k8s.io/api/core/v1".RBDPersistentVolumeSource

### ISSUE THREAD

**Issue by wcg2008zl** [kubernetes/api#10]
hi:
 when I build kubectl on my PC,  I found this error:'undefined: "k8s.io/api/core/v1".RBDPersistentVolumeSource' ,  and i  cant find "RBDPersistentVolumeSource" defined in the package "k8s.io/api/core/v1" , how to fix this ? thanks !

**Comment by nikhita** [comment]
@wcg2008zl Can you elaborate what steps you took to build kubectl?
