### ISSUE TITLE
v1.11.0-beta.X releases does not exist

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/api#16]
From https://github.com/kubernetes/kubernetes/releases, both `v1.11.0-beta.1` and `v1.11.0-beta.0` are tagged in kubernetes/kubernetes, would the same version be tagged here as well? I did see the alpha one (e.g. `kubernetes-1.11.0-alpha.2`) but not beta.

(We are experiencing some compilation issue while updating vendor.)

**Comment by dims** [comment]
cc @calebamiles

**Comment by nikhita** [comment]
They exist now.

Also, `kubernetes-1.12.0-alpha.0` exists.

Closing.
/close
