### ISSUE TITLE
busted go get's with go modules

### ISSUE THREAD

**Issue by jmhodges** [kubernetes/api#26]
When installing various pieces of k8s tools, I keep running into this error from `go get` (and its module support):

```
$  go get -d github.com/rancher/rancher
[.. elided ..]
go: k8s.io/kubernetes@v1.16.1 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```

(This feels like maybe a tag got made that wasn't supposed to?)

**Comment by carnott-snap** [comment]
This is an issue with `github.com/rancher/rancher` importing `k8s.io/kubernetes@v1.16.1`. Instead it should be importing component libraries directly:
- do this: `import k8s.io/api`
- not this: `import k8s.io/kubernetes/pkg/api`
- context: kubernetes/kubernetes#81878

**Comment by jianzhangbjz** [comment]
Get the same issue when initing the `go.mod`. How to fix it? Thanks!
```console
mac:openshift-tests-private jianzhang$ go build ./...
go: finding github.com/openshift/openshift-tests latest
go: finding github.com/openshift/library-go latest
go: finding github.com/RangelReale/osincli latest
go: k8s.io/kubernetes@v1.18.1 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```
