### ISSUE TITLE
ResourceQuota: Hard and Used are not ResourceList

### ISSUE THREAD

**Issue by alidadar7676** [kubernetes/api#31]
When I was using ResourceQuotaStatus.Hard, I found a mistake. `Hard` and `Used` are ResourceList, but actually they are not.

When you define `Hard` as a ResourceList, I can call methods of `ResourceList` on it, So I can call `ResourceQuota.Status.Hard.CPU()` for example, but it returns nothing because `Hard` contains `Limits` and `Requests` like `ResourceRequirements` type.

I know you define some constants for getting `requests` and `limits` from the `Hard`'s `ResourceList` map(like `ResourceRequestsCPU`).

Can you explain why you didn't use `ResourceRequirements` as the type of the `Hard` or `Used`?
Can I fix it by changing types to `ResourceRequirements`?

**Comment by SergeyKanzhelev** [comment]
you may have better luck filing issue on the main kubernetes repository. This is just a mirror repo and it is not monitored for issues. See https://github.com/kubernetes/api#things-you-should-not-do

/close
