### ISSUE TITLE
missing tag for 0.20.0-rc.0

### ISSUE THREAD

**Issue by smira** [kubernetes/api#35]
This repo and other Go modules repos under kubernetes seem to be missing a tag for 1.20.0-rc.0 (https://github.com/kubernetes/kubernetes/releases/tag/v1.20.0-rc.0).

**Comment by nikhita** [comment]
/assign

I'll create a PR in the next hour to fix this :)

**Comment by smira** [comment]
@nikhita thanks for quick response, but looks like tag is still missing for 0.20.0-rc.0, e.g. for `apimachinery` package:

![image](https://user-images.githubusercontent.com/55211/100881349-deb88f80-34be-11eb-9bcf-c66b978df0e6.png)

**Comment by nikhita** [comment]
@smira https://github.com/kubernetes/kubernetes/pull/97004 will fix it :+1:

**Comment by smira** [comment]
> [kubernetes/kubernetes#97004](https://github.com/kubernetes/kubernetes/pull/97004) will fix it +1

thank you!

**Comment by nikhita** [comment]
@smira the rc tag is available now :smile: 

https://github.com/kubernetes/api/releases/tag/v0.20.0-rc.0

**Comment by smira** [comment]
thanks @nikhita, it's working now, so we can actually upgrade to 1.20.0-rc.0!
