### ISSUE TITLE
Question: when will be release v0.21.0 approximately?

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [kubernetes/api#36]
Sorry, guys, maybe that's wrong place for question, but when will be release v0.21.0 approximately?

**Comment by nikhita** [comment]
@AndrienkoAleksandr it'll be released once Kubernetes v1.21.0 is released, which is on April 8 - https://github.com/kubernetes/sig-release/tree/master/releases/release-1.21#timeline

Just as a heads up, there is usually a ~4 hour lag between the time when the Kubernetes version is released and the `v0.21.0` tag shows up on this repo.
