### ISSUE TITLE
DeploymentStatus readyReplicas docstring needs clarification.

### ISSUE THREAD

**Issue by briantkennedy** [kubernetes/api#38]
https://github.com/kubernetes/api/blob/master/apps/v1/types.go#L411

The docstring defines `readyReplicas` as "Total number of ready pods targeted by this deployment" which is defining "ready" in terms of being "ready".  Please clarify the docstring on what "ready" means in this context since the docstring is used for the user-facing docs at https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/.  

Fixing this will also resolve https://github.com/kubernetes/website/issues/28316

**Comment by matthiasgubler** [comment]
@briantkennedy As I understood, the documentation should be clarified to describe that a pod is defined as ready when it's passing the defined probes. Is that correct? 

By reviewing the mentioned page [Deployment](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/), I saw that  [ReplicaSet#ReplicaSetStatus](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/replica-set-v1/#ReplicaSetStatus), [ReplicationController#ReplicationControllerStatus](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/replication-controller-v1/), and [DaemonSet#DaemonSetStatus](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/#DaemonSetStatus) have similar descriptions with an equivalent grade of unclarity.

I would suggest rewriting all those docs to something like `readyReplicas is the number of Pods targeted by this Deployment that have a Ready Condition.` equivalent to the docs of [StatefulSet#StatefulSetStatus](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/stateful-set-v1/#StatefulSetStatus).

If you approve this, I will open a PR and do it for all the mentioned docs.

**Comment by briantkennedy** [comment]
Thanks for taking a look.  You are correct, adding the criteria for ready is what I'm looking for.  For clarity, what are the defined probes you are referring to?

**Comment by matthiasgubler** [comment]
I'm referring to the readiness probes. Thanks for the Feedback, the PR will follow soon.
