### ISSUE TITLE
Not syncing?

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/api#4]
Seems the repo hasn't synced for a week.

**Comment by nikhita** [comment]
related: https://github.com/kubernetes/kubernetes/issues/51643

**Comment by sttts** [comment]
@feiskyer we have no bot syncing right now. The `k8s.io/*` sync was manually done with the branches of last Wednesday.

If you want more up-to-date branches, take a look at my (experimental) fork: https://github.com/sttts/client-go

**Comment by feiskyer** [comment]
@sttts Why no bots syncing now? Are there any ways to make them sync again

**Comment by dims** [comment]
@feiskyer you can follow https://github.com/kubernetes/test-infra/issues/4080 for progress

**Comment by sttts** [comment]
> Why no bots syncing now? Are there any ways to make them sync again

Simply lack of time of the people involved and other high prio topics for 1.8. Here is the PR https://github.com/kubernetes/test-infra/pull/4134. Reviews are welcome, though this is still work in progress.

**Comment by nikhita** [comment]
The bot is active and running now. 🎉 

https://github.com/kubernetes/publishing-bot

I believe this issue can be closed.
