### ISSUE TITLE
Can not specify pod name

### ISSUE THREAD

**Issue by serend1p1ty** [kubernetes/api#43]
Hi, the repo is excellent! It works well except I can not specify the pod name. Can anyone help me? I will be very grateful!
I have tried specified `ObjectMeta.Name` as shown in the following image, but it does not work.
![image](https://user-images.githubusercontent.com/39628662/185830227-c8f3d93f-d4ca-48a7-ad84-b37f4d710b50.png)

**Comment by kundan2707** [comment]
@serend1p1ty  Can you describe what exactly you want to do?
provide sequence of operations and setup information

**Comment by kundan2707** [comment]
@serend1p1ty 
https://github.com/kubernetes/kubernetes/issues/113952#issuecomment-1317042694

**Comment by kundan2707** [comment]
@serend1p1ty  have you resolved your issue ?

**Comment by kundan2707** [comment]
@serend1p1ty  if there is nothing pending we can close it.
