### ISSUE TITLE
v1.AdmissionRequest does not implement runtime.Object interface

### ISSUE THREAD

**Issue by imilchev** [kubernetes/api#44]
I noticed that [v1.AdmissionRequest](https://github.com/kubernetes/api/blob/master/admission/v1/types.go#L40-L113) does not implement the `runtime.Object` interface. I am curious if there is a specific reason for not doing that. Right now I need to work around this since I cannot assign `v1.AdmissionRequest` to `runtime.Object` variables

**Comment by liggitt** [comment]
AdmissionReview is the top-level object that is serializes/deserialized, and implements runtime.Object

AdmissionRequest and AdmissionResponse are nested substructs and do not implement that interface, but they are also not intended to be serialized independently, only in the context of the parent AdmissionReview object which has identifying apiVersion/kind information
