### ISSUE TITLE
kubectl explain node / oc explain node delivers wrong information

### ISSUE THREAD

**Issue by erdincay** [kubernetes/api#47]
**What happened**:

I executed `oc explain node` and received wrong information what a node is. It stated that a node is a worker node, which is wrong.

The information comes from: api/core/v1/types_swagger_doc_generated.go 
"":         "Node is a worker node in Kubernetes. Each node will have a unique identifier in the cache (i.e. in etcd).",

**What you expected to happen**:

I expected it to write: a node is a worker node **or a master node**.

**How to reproduce it (as minimally and precisely as possible)**:

`oc explain node`

**Anything else we need to know?**:

Open Shift Version from `oc version`:
![grafik](https://user-images.githubusercontent.com/11290149/220595689-1dd10011-ca16-41c3-8744-12645f4c02ba.png)

**Environment**:

RHEL 8.6, platform:el8

**Comment by kundan2707** [comment]
kubectl explain node do not contain any data like mater or worker. if oc explain node giving some wrong data it should be fixed there

**Comment by kundan2707** [comment]
@erdincay gentle reminder if it still persist

**Comment by erdincay** [comment]
> @erdincay gentle reminder if it still persist

I cannot reproduce it anymore, due to being not able to access the machine anymore. Thanks for the reminder. Close this ticket, if you wan. If I should get a chance to test it again, I will create a repost or reopen this ticket.

**Comment by kundan2707** [comment]
closing this one as not reproducible as of now.
Feel free to repoen whenever you face it again
