### ISSUE TITLE
Reuse the IngressLoadBalancerStatus structure

### ISSUE THREAD

**Issue by fengshunli** [kubernetes/api#49]
Why don't v1beta1.IngressLoadBalancerStatus and networking v1.IngressLoadBalancerStatus and corev1.LoadBalancerStatus and v1.LoadBalancerStatus reuse the same structure, so that the upper layer call will be more convenient

Versions before 1.26 returned v1.LoadBalancerStatus, why was version 1.26 removed?
![image](https://github.com/kubernetes/api/assets/18587688/21ee410c-193e-4c4d-9952-6f9be384f069)

For example
<img width="462" alt="image" src="https://github.com/kubernetes/api/assets/18587688/6fe7f38a-dd4f-4976-8bf4-b1f86c53c6c3">

**Comment by szuecs** [comment]
Make sure you do not remove things from the ingress status, otherwise external-dns would not work for ingress, which is the main purpose of it.

**Comment by fengshunli** [comment]
After upgrading the API of 1.26, the structure has changed

**Comment by szuecs** [comment]
Maybe I miss something but https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressStatus shows `loadBalancer.ingress.hostname` for example. I guess there are only added data, no? 

```go
// IngressLoadBalancerStatus represents the status of a load-balancer.
type IngressLoadBalancerStatus struct {
	// ingress is a list containing ingress points for the load-balancer.
	// +optional
	Ingress []IngressLoadBalancerIngress `json:"ingress,omitempty" protobuf:"bytes,1,rep,name=ingress"`
}

// IngressLoadBalancerIngress represents the status of a load-balancer ingress point.
type IngressLoadBalancerIngress struct {
	// ip is set for load-balancer ingress points that are IP based.
	// +optional
	IP string `json:"ip,omitempty" protobuf:"bytes,1,opt,name=ip"`

	// hostname is set for load-balancer ingress points that are DNS based.
	// +optional
	Hostname string `json:"hostname,omitempty" protobuf:"bytes,2,opt,name=hostname"`

	// ports provides information about the ports exposed by this LoadBalancer.
	// +listType=atomic
	// +optional
	Ports []IngressPortStatus `json:"ports,omitempty" protobuf:"bytes,4,rep,name=ports"`
}
```
source tree in master

**Comment by szuecs** [comment]
Ah I see v0.25
```
type IngressStatus struct {
	// LoadBalancer contains the current status of the load-balancer.
	// +optional
	LoadBalancer v1.LoadBalancerStatus `json:"loadBalancer,omitempty" protobuf:"bytes,1,opt,name=loadBalancer"`
}
```

and v0.26 
```
type IngressLoadBalancerStatus struct {
	// Ingress is a list containing ingress points for the load-balancer.
	// +optional
	Ingress []IngressLoadBalancerIngress `json:"ingress,omitempty" protobuf:"bytes,1,rep,name=ingress"`
}
```

**Comment by aojea** [comment]
it is explained in the PR https://github.com/kubernetes/kubernetes/pull/106242 
Ingress and Loadbalancer used the same fields until 1.26, but the one got new fields that does not apply to the other

**Comment by fengshunli** [comment]
> That is correct - the shape of the struct determines the API, not the Go struct type names (they are not part of the public API).

@smarterclayton @aojea The attributes in this structure are the same, why not continue the design before 1.26, and use a public structure to return, which is more conducive to upper-level calls, isn’t it more reasonable?

**Comment by fengshunli** [comment]
If each type returns its own internal structure, this increases the complexity of the upper-level call, and the same set of code needs to maintain three copies

**Comment by fengshunli** [comment]
<img width="1009" alt="image" src="https://github.com/kubernetes/api/assets/18587688/da736e12-a0ce-4e65-b85a-29c56fc6923e">

@aojea I get each Ingress and do the same operation, and now it cannot be shared, which will cause my same implementation to be unable to call directly
