### ISSUE TITLE
Can't upgrade to k8s.io/api v0.28.0-alpha.4

### ISSUE THREAD

**Issue by tonsV2** [kubernetes/api#51]
Dependabot is trying to upgrade my project with the following dependencies

	k8s.io/api v0.28.0-alpha.4
	k8s.io/apimachinery v0.28.0-alpha.4
	k8s.io/client-go v0.28.0-alpha.4

However when I try to compile I get the following error

	#14 [build 8/8] RUN go build -o /app/im-manager -ldflags "-s -w" ./cmd/serve
	#14 31.08 # sigs.k8s.io/kustomize/kyaml/openapi
	#14 31.08 /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/openapi/openapi.go:656:33: cannot use doc (variable of type *"github.com/google/gnostic/openapiv2".Document) as *"github.com/google/gnostic-models/openapiv2".Document value in argument to swagger.FromGnostic
	#14 ERROR: process "/bin/sh -c go build -o /app/im-manager -ldflags \"-s -w\" ./cmd/serve" did not complete successfully: exit code: 1

The project in question can be found [here](https://github.com/dhis2-sre/im-manager).

Please let me know if I should add more information or ask in a different place.

**Comment by tamilselvan1102** [comment]
May be this https://github.com/kubernetes/client-go/issues/1075 would help to resolve your issue.
