### ISSUE TITLE
Deprecation of "github.com/gogo/protobuf"

### ISSUE THREAD

**Issue by imJayanth** [kubernetes/api#54]
`"k8s.io/api"` is using the deprecated `"github.com/gogo/protobuf"`
 Is it possible to remove this deprecated module and replace it with a suitable alternative?

**Comment by julianguinard** [comment]
I would add this breaks reflection on projects based on the  more up-to-date and still maintained [google.golang.org/protobuf](google.golang.org/protobuf) module

Given the following `test.proto` in such a project using `google.golang.org/protobuf` and importing importing k8s.proto :

```proto
syntax = "proto3";
package test.v1;

import "k8s.io/api/core/v1/generated.proto";
```
running reflection query like `grpc_cli ls localhost:8080 -l` would generate the following error

```
Invalid proto descriptor for file "v1/test.proto":
[libprotobuf ERROR git/grpc/third_party/protobuf/src/google/protobuf/descriptor.cc:4202]   k8s.io/api/core/v1/generated.proto: Import "k8s.io/api/core/v1/generated.proto" was not found or had errors.
```
