### ISSUE TITLE
Remove developer comment from `LocalObjectReference`

### ISSUE THREAD

**Issue by mateusoliveira43** [kubernetes/api#69]
Remove this comment here
https://github.com/kubernetes/api/blob/ffee488e7bd8c76c62b4646310580a1a6d7243b8/core/v1/types.go#L6419

It gets propagated as description of the field `Name` and it appears in descriptions of CRDs delivered to users.

As a suggestion, remove the comment and create an issue to address it.

Thanks :smile:

**Comment by wanj1ru** [comment]
assign

**Comment by wanj1ru** [comment]
this issue is already solved

/close

**Comment by kundan2707** [comment]
closing as it is already resolved
