### ISSUE TITLE
`Divisor` `resource.Quantity` `omitempty` doesn't make sense

### ISSUE THREAD

**Issue by regnaio** [kubernetes/api#75]
https://github.com/kubernetes/api/blob/master/core/v1/types.go#L2309

When you `json.Marshal()` a `ResourceFieldSelector` with undefined `Divisor`, you get `divisor: "0"`

This is bad for 2 reasons:
1. `omitempty` is meaningless here
2. According to the docs, `Divisor` should default to `1`. Since it actually defaults to `0`, you get unintended behavior and incorrect results

`Divisor` instead should be a pointer `*resource.Quantity` instead of just `resource.Quantity`

**Comment by wanj1ru** [comment]
tried pushing my commit i got permission denied

**Comment by dims** [comment]
please open a PR in https://github.com/kubernetes/kubernetes/ this repo is auto-generated from the code in that original repository
